---
# Tasks for GitLab EE installation using Omnibus package

- name: Ensure Docker is installed
  include_role:
    name: docker

- name: Install required dependencies
  apt:
    name:
      - curl
      - openssh-server
      - ca-certificates
      - tzdata
      - perl
    state: present
    update_cache: yes

- name: Add GitLab repository GPG key
  apt_key:
    url: https://packages.gitlab.com/gitlab/gitlab-ee/gpgkey
    state: present

- name: Add GitLab repository
  apt_repository:
    repo: "deb https://packages.gitlab.com/gitlab/gitlab-ee/ubuntu/ {{ ansible_distribution_release }} main"
    state: present
    filename: gitlab-ee
    update_cache: yes

- name: Configure GitLab external URL
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: "^external_url "
    line: "external_url '{{ gitlab_external_url }}'"
    create: yes
  register: gitlab_config

- name: Configure GitLab SSH port
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: "^gitlab_rails\\['gitlab_shell_ssh_port'\\]"
    line: "gitlab_rails['gitlab_shell_ssh_port'] = {{ gitlab_ssh_port }}"
    create: yes
  register: gitlab_config

- name: Disable SMTP
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: "^gitlab_rails\\['smtp_enable'\\]"
    line: "gitlab_rails['smtp_enable'] = false"
    create: yes
  register: gitlab_config

- name: Configure backup path
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: "^gitlab_rails\\['backup_path'\\]"
    line: "gitlab_rails['backup_path'] = '{{ gitlab_backup_path }}'"
    create: yes
  when: gitlab_backup_enabled
  register: gitlab_config

- name: Configure backup retention
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: "^gitlab_rails\\['backup_keep_time'\\]"
    line: "gitlab_rails['backup_keep_time'] = {{ gitlab_backup_keep_time }}"
    create: yes
  when: gitlab_backup_enabled
  register: gitlab_config

- name: Install GitLab EE package
  apt:
    name: gitlab-ee={{ gitlab_version }}
    state: present
  environment:
    EXTERNAL_URL: "{{ gitlab_external_url }}"

- name: Reconfigure GitLab
  command: gitlab-ctl reconfigure
  when: gitlab_config.changed

- name: Wait for GitLab to become available
  uri:
    url: "{{ gitlab_external_url }}"
    status_code: 200
    timeout: 5
  register: gitlab_status
  until: gitlab_status.status == 200
  retries: 60
  delay: 10
  ignore_errors: true

- name: Display GitLab access information
  debug:
    msg: |
      GitLab has been installed and should be available at {{ gitlab_external_url }}
      
      Initial root password can be retrieved with:
      sudo cat /etc/gitlab/initial_root_password
      
      Note: This password is valid for 24 hours after installation.