---
- name: Install Docker
  hosts: all
  become: true
  
  roles:
    - docker
  
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_os_family == "Debian"
      
  post_tasks:
    - name: Verify Docker installation
      command: docker --version
      register: docker_version
      changed_when: false
      
    - name: Display Docker version
      debug:
        msg: "Docker is now installed: {{ docker_version.stdout }}"