---
# Host-specific variables for GitLab server

# GitLab version (use specific version or leave empty for latest)
# Format: "18.4.0-ee.0" or leave empty for latest
gitlab_version: ""  # Empty means latest version

# GitLab configuration
gitlab_hostname: "192.168.0.6"
gitlab_external_url: "http://192.168.0.6"
gitlab_home: "/var/opt/gitlab"

# GitLab ports
gitlab_http_port: 80
gitlab_https_port: 443
gitlab_ssh_port: 2222  # Using port 2222 for SSH to avoid conflict with system SSH

# Backup configuration
gitlab_backup_enabled: true
gitlab_backup_path: "/var/opt/gitlab/backups"
gitlab_backup_keep_time: "604800"  # 7 days in seconds

# SMTP configuration (disabled by default)
gitlab_smtp_enabled: false
# Uncomment and modify these settings to enable email
# gitlab_smtp_address: "smtp.example.com"
# gitlab_smtp_port: 587
# gitlab_smtp_user_name: "smtp_user"
# gitlab_smtp_password: "smtp_password"
# gitlab_smtp_domain: "example.com"